extends: [ 
  eslint:recommended,
  prettier,
  prettier/react,
  react-app,
]
parser: 'babel-eslint'
env: {
  es6: true,
  jest: true
}
rules: {
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
}
settings: {
  import/ignore: ['node_modules', '\\.(svg|json)$'],
}